FROM postgres:9.5

ENV POSTGRES_USER docker
ENV POSTGRES_PASSWORD secret
ENV POSTGRES_DB todo_app

# create DB when docker init, without create_db.py
#ADD ./etc/schema.sql /docker-entrypoint-initdb.d/
